# Generated by Django 5.2.7 on 2025-11-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_description_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
